In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn import neighbors

In [2]:
dataset = load_iris()
df = pd.DataFrame(dataset['data'], columns = dataset['feature_names'])
df['target'] = dataset['target']
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [3]:
df.groupby('target').size()

target
0    50
1    50
2    50
dtype: int64

In [4]:
setosa = df[df['target'].values == 0]
versicolor = df[df['target'].values == 1]
virginica = df[df[ 'target'].values == 2]

In [5]:
setosa.describe()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
count           50.00000         50.000000  ...         50.000000    50.0
mean             5.00600          3.428000  ...          0.246000     0.0
std              0.35249          0.379064  ...          0.105386     0.0
min              4.30000          2.300000  ...          0.100000     0.0
25%              4.80000          3.200000  ...          0.200000     0.0
50%              5.00000          3.400000  ...          0.200000     0.0
75%              5.20000          3.675000  ...          0.300000     0.0
max              5.80000          4.400000  ...          0.600000     0.0

[8 rows x 5 columns]

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()
feature = iris.data
label = iris.target

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors =4)
knn.fit(feature, label)
a = np.array([[2.0,1.2,3.4,3.7]])
knn.predict(a)

array([1])

In [7]:
knn = KNeighborsClassifier(n_neighbors =6)
knn.fit(feature, label)
a = np.array([[2.0,1.2,3.4,3.7]])
knn.predict(a)

array([1])

In [8]:
knn = KNeighborsClassifier(n_neighbors =8)
knn.fit(feature, label)
a = np.array([[2.0,1.2,3.4,3.7]])
knn.predict(a)

array([1])

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(feature, label, test_size = 0.20)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
from sklearn.model_selection import GridSearchCV
params = {'n_neighbors':[2,3,4,5,6,7,8,9,10]}

knn = neighbors.KNeighborsClassifier()

model = GridSearchCV(knn, params, cv=5)
model.fit(x_train,y_train)
model.best_params_

{'n_neighbors': 7}

In [15]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier (n_neighbors = 7)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [16]:
y_pred = classifier.predict(x_test)

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0 11  0]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.92      1.00      0.96        11
           2       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

